version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/yaru_window_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/yaru_window_manager"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/yaru_window_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/yaru_window_web"
    schedule:
      interval: "daily"
